name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - name: Compile Windows version
      - run: elm make src/Main.elm
      
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1      
      - name: Compile Mac/Linux version
      - run: elm make src/Main.elm
